
import React from 'react';
import { 
  Users, 
  BrainCircuit, 
  TrendingUp, 
  Mic2, 
  MapPin, 
  Trophy 
} from 'lucide-react';
import { GameMetadata, Team } from './types';

export const GAMES: GameMetadata[] = [
  {
    id: 'bingo',
    title: 'BINGO Networking',
    description: 'Connect with fellow engineers and check off your tech network grid.',
    icon: 'Users',
    externalLink: 'https://hoogo.makemypass.com',
    color: 'from-purple-500 to-indigo-600'
  },
  {
    id: 'mindclans',
    title: 'MINDCLANS',
    description: 'A fierce team-based guessing game that tests your collective logic.',
    icon: 'BrainCircuit',
    color: 'from-blue-500 to-purple-600'
  },
  {
    id: 'sell',
    title: 'SELL THE PRODUCT',
    description: 'Market real-world items to simulated buyers and rack up revenue.',
    icon: 'TrendingUp',
    color: 'from-emerald-500 to-teal-600'
  },
  {
    id: 'pitch',
    title: 'PITCH THE PRODUCT',
    description: 'Innovate on the fly with random products generated by our Core AI.',
    icon: 'Mic2',
    color: 'from-pink-500 to-rose-600'
  },
  {
    id: 'treasure',
    title: 'TREASURE HUNT',
    description: 'Decipher cryptic clues hidden across the entire campus grid.',
    icon: 'MapPin',
    externalLink: 'https://treasure-hunt.ieee.org',
    color: 'from-orange-500 to-amber-600'
  }
];

export const INITIAL_TEAMS: Team[] = []; // Started empty as per request

export const ICONS: Record<string, React.ReactNode> = {
  Users: <Users className="w-8 h-8" />,
  BrainCircuit: <BrainCircuit className="w-8 h-8" />,
  TrendingUp: <TrendingUp className="w-8 h-8" />,
  Mic2: <Mic2 className="w-8 h-8" />,
  MapPin: <MapPin className="w-8 h-8" />,
  Trophy: <Trophy className="w-8 h-8" />,
};
